name: teslo_shop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  animate_do: ^3.1.2
  audioplayers: ^5.2.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_downloader: ^1.11.4
  flutter_file_downloader: ^1.1.4
  flutter_riverpod: ^2.3.2
  formz: ^0.6.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  html: ^0.15.4
  path_provider: ^2.1.1
  pdf: ^3.10.4
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  syncfusion_flutter_pdfviewer: ^23.1.39

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
